# -*- coding: utf-8 -*-
"""Weather_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_cvyfeNnDTs2Suv714LC4ElGxgiLiNf

**Weather Data Analysis Report**

**Objective**

To analyze weather data using Python and identify trends in temperature, humidity, and rainfall.

**Tools Used**

1. Python
2. Pandas
3. Matplotlib
4. Seaborn

**Analysis Performed**

1. Average temperature analysis
2. Average humidity analysis
3. Monthly rainfall analysis
4. Monthly temperature comparison

**Visualizations**

1. Temperature Trend
2. Humidity Trend
3. Average Monthly Temperature
4. Monthly Rainfall Comparison
"""

pip install pandas matplotlib seaborn numpy

import pandas as pd

df = pd.read_csv("climate_data.csv")

print(df.head())
print(df.info())

# Check missing values
print(df.isnull().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Convert Date column
df["Date"] = pd.to_datetime(df["Date"])

# Temperature Analysis
print("Average Temperature:")
print(df["Average temperature (°F)"].describe())

# Humidity Analysis
print("Average Humidity:")
print(df["Average humidity (%)"].describe())

# Rainfall Analysis
monthly_rain = df.groupby("Month")["Rainfall for month (in)"].mean()
print(monthly_rain)

# Monthly Temperature

monthly_temp = df.groupby("Month")["Average temperature (°F)"].mean()
print(monthly_temp)

# Graph 1

import matplotlib.pyplot as plt
plt.figure(figsize=(12,5))
plt.plot(df["Date"], df["Average temperature (°F)"])
plt.title("Temperature Trend")
plt.xlabel("Date")
plt.ylabel("Temperature (°F)")
plt.grid(True)
plt.savefig("temperature_trend.png")
plt.show()

# Graph 2

import seaborn as sns
plt.figure(figsize=(12,5))
sns.lineplot(data=df,x="Date",y="Average humidity (%)")
plt.title("Humidity Trend")
plt.savefig("humidity_trend.png")
plt.show()

# Graph 3

plt.figure(figsize=(8,5))
monthly_temp.plot(kind="bar")
plt.title("Average Monthly Temperature")
plt.ylabel("Temperature (°F)")
plt.savefig("monthly_temperature.png")
plt.show()

# Graph 4

plt.figure(figsize=(8,5))
monthly_rain.plot(kind="bar")
plt.title("Average Monthly Rainfall")
plt.ylabel("Rainfall (inches)")
plt.savefig("monthly_rainfall.png")
plt.show()

"""**Insights**


*   Temperature varies throughout the year with noticeable seasonal changes.

*  Humidity levels fluctuate across different months.

*  Rainfall differs by month, indicating seasonal precipitation patterns.

*  Monthly comparison clearly shows weather changes over time.

**Conclusion**

The project successfully analyzed the weather dataset and visualized important weather patterns using Python.
"""